### ISSUE TITLE
可以支持 Construct 3 引擎吗？

### ISSUE THREAD

**Issue by XHXIAIEIN** [fairygui/FairyGUI-dom#10]
Construct 3 (https://editor.construct.net/) 是一个基于浏览器的游戏引擎，通过 Webview 运行，可以导出到各平台。这是引擎官方的[插件开发文档](https://www.construct.net/en/make-games/manuals/addon-sdk)，官方也提供了一些插件的[开源案例](https://github.com/Scirra/Construct-Addon-SDK)，插件支持 JavaScript 和 TypeScript 编码，也支持插件使用 C++ 集成。理论上其他 H5 引擎能运行，那么在C3运行也没有问题的。

C3 引擎缺少一种通用UI的解决方案，目前只能依赖硬编码或者原生DOM，如果 FairyGUI 能支持C3就真的能极大提高工作效率。

**Comment by xiaoguzhu** [comment]
谢谢你的信息。但首先，他是收费软件。
